/************
alberto
curcuferencia.java
the programs gives us the area of a circumference
************/
double r, pi, area  real;
public class circuferenciaa {
     public static void main(String[] args) {
       double r,pi;
       System.out.println("Ingresa radio");
       r=sc.nextDouble();
       System.out.println("Ingresa pi");
       pi=sc.nextDouble();
       double area;
       area=pi*r;
      System.out.print(area);
     }
   }
