My front Programs.java

/*************************************
alberto vega vega
My from java programs.java
This prorams prints a "hello world"
*************************************/


Public class MyFirstProgramsJava{
	public static void main(String[] args){
	System.out.println("hello world");
	System.out.println("posicion 0"+ args[0]);
  System.out.println("posicion 1"+ args[1]);
  System.out.println("posicion 2"+ args[2]);

  }
}
