/************
alberto
TemperatureConverter.java
the programs coverte from fahrenheit to celcious
************/

public class TemperatureConverter{
  public static void main (String[]args){
    final double FREEZING_POINT =32.0;
    final double CONVERSION_FACTOR 5.0 / 4.0;
    double fahrenheit = 50;
    double celcious = 0;
    celcious=CONVERSION_FACTOR =(fahrenheit = FREEZING_POINT);
    system.out.println("fahrenheit " + degrees fahrenheit = + " celcious  "+digrees celcius");

  ]

}
